### ISSUE TITLE
SD Manual - batch file error re --config

### ISSUE THREAD

**Issue by rgleason** [Rasbats/managed_plugins#14]
When the batch file  bld-no-clone.bat is executed it results in an error message due to the first --config

See  https://github.com/Rasbats/shipdriver_pi/issues/232#issuecomment-951249356

`CMake Error: Unknown argument --config                 <-----ERROR GENERATED BY FIRST COMMAND`

See this thread
https://github.com/Rasbats/shipdriver_pi/issues/263

**Comment by leamas** [comment]
Continued from  https://github.com/Rasbats/shipdriver_pi/issues/263

> When the batch file bld-no-clone.bat

We need to be specific here. That file is actually not part of the shipdriver templates, and there are no instructions that it could or should be copied to another location. This basically means that the issue is moot.

As a fresh start: please try to reproduce your problem(s) using the scripts which actually are available in the templates (ShipDriver.clone.bat  and ShipDriver.without.clone.bat),  modified but not moved  as of the comment in them. That would create  a common starting point.
